### PR TITLE
Fix CoinGecko Invalid Hook Call Error

### PR DESCRIPTION
**Pull request by javonmcgilberry**
It appears that the coingecko package is incorrectly specifying react as a dependency **rather than a peer dependency**. [Please see here in react docs for more details](https://reactjs.org/warnings/invalid-hook-call-warning.html). 

Under its current form, this results in 2 copies of react. The application breaks with the latest release of React Version 18, because we have hardcoded version 17 (as a workaround the user is now forced to do an npm link)

Interestingly enough, this peer dependency detail is already something we are doing for the core useDApp package, so perhaps this was overlooked by mistake :)

### CODE REVIEW

**Comment by rzadp** [comment]
@javonmcgilberry Good catch.
You need to regenerate lockfile - `pnpm install` and commit the changes.

**Comment by javonmcgilberry** [comment]
Sorry about that! @rzadp . I believe we should be good now

**Review by mj426382 — COMMENTED** [review]
Remove pnpm-lock.yaml and run pnpm install && pnpm build and then push changes.

**Review by rzadp — APPROVED** [review]

**Comment by javonmcgilberry** [comment]
alright guys we should be good now 😅

**Pull request closed without merging**
