### PR TITLE
✍️ Add usedeepmemo usecallback imrpovements

### PR DESCRIPTION
**Pull request by sirpy**
see #1035 for context
Added usage of deep equal in useRawCalls and useLogs which should reduce re-renders dependent on the results as input params.
Also improved useEthers not to return inline function but rather useCallback

### CODE REVIEW

**Comment by sirpy** [comment]
#1035 
@rzadp

**Comment by rzadp** [comment]
@pawelpolak2 You could contribute by adding a clever test that would count the number of rerenders.
The test should be red before this change and green after this change.

**Comment by sirpy** [comment]
@rzadp sorry don't have the bandwidth for that. i've verified the deep compare works so things like logs do not change, and that it improved our re-renders also the usecallback improvements are obvious but i've also verified they stopped some of the re-renders we were having

**Comment by rzadp** [comment]
> @rzadp sorry don't have the bandwidth for that.

Yes that is completely fine, please note that I have tagged someone else for that :)

**Review by yivlad — APPROVED** [review]

**Comment by sirpy** [comment]
@yivlad why was this closed?

**Comment by yivlad** [comment]
@sirpy most of the changes were already added in other PRs. The only thing that is not implemented is `useDeepMemo` hook, and I played around with it a bit and it doesn't really seem to help. Besides I would prefer not to add additional external dependencies.

**Comment by sirpy** [comment]
@yivlad 
first can you point me to the PR where useEtherrs is fixed to use useCallback correctly + deps?

secondly i'm not sure what you mean by it doesnt really seem to help, you are probably not testing things correctly.
you do understand that useMemo has absolutely 0 effect when dealing with arrays and objects that are being re-created on each render?

```
const logs = useLogs()
<SomeComponent logs={logs}/>
```
in the above case without the deep memo SomeComponent would be re-rendered everytime your global store changes.

the only case where usedeepmemo would in did not have much effect is inside useRawCalls, because that depends on "chains" directly.

**Comment by yivlad** [comment]
@sirpy 
Here is [the PR](https://github.com/TrueFiEng/useDApp/pull/1058) I'm talking about.

Giving this a second thought though I think it actually would make sense to use `useDeepMemo` in the `useLogs` hook. I think this is also what you're saying as well? If so, you can  open another PR with this changes? I would also like to use [this](https://github.com/apollographql/apollo-client/blob/master/src/react/hooks/utils/useDeepMemo.ts) implementation of the useDeepMemo hook. It introduces less external dependencies and also handles the case of cycle references.

**Comment by sirpy** [comment]
@yivlad well it makes sense to use it anywhere you use "usememo" with non primitives like arrays/objects.
I dont see how this is less dependencies, unless you mean you want to include the source code.

**Comment by yivlad** [comment]
@sirpy exactly, I think the best option is to copy the code of the `useDeepMemo` hook. We'll have to introduce only one dependency that doesn't have any other dependencies (`@wry/equality`)

**Pull request closed without merging**
