### PR TITLE
🥶 Adding avalanche testnet

### PR DESCRIPTION
**Pull request by jacobmakarsky**
added avalanche testnet, I believe this is their multicall contract address, I retrieved it from https://github.com/makerdao/multicall/pull/32

thank you 👍

### CODE REVIEW

**Comment by jacobmakarsky** [comment]
is something wrong with it?

**Comment by jacobmakarsky** [comment]
fixed up the yarn lint stuff

**Comment by jacobmakarsky** [comment]
looks like its all good to go i think 👌 would like to use it for testing if it can be merged soon, thank you

**Comment by tt-marek** [comment]
@jacobmakarsky Looks good ❤️  Would you verify the contract before merge?

**Comment by chand1012** [comment]
Any update on this? Use of this library would make development on Avalanche really easy for React devs. :slightly_smiling_face:

**Pull request merged**
