### PR TITLE
⛓ Adding Optimism Göerli

### PR DESCRIPTION
**Pull request by afa7789**
Closes https://github.com/TrueFiEng/useDApp/issues/877

### CODE REVIEW

**Review by rzadp — APPROVED** [review]
Thanks for picking this up.

**Comment by rzadp** [comment]
@afa7789 Can you correct the linting please?

**Comment by afa7789** [comment]
sure

**Comment by afa7789** [comment]
@rzadp done

**Review by rzadp — APPROVED** [review]

**Comment by afa7789** [comment]
I was still getting some test errors here, I believe you solved it with the master merge ? Not sure.

**Comment by yivlad** [comment]
> I was still getting some test errors here, I believe you solved it with the master merge ? Not sure. ( if you merged already you can close the PR lol )

Please fix the tests [here](https://github.com/afa7789/useDApp/blob/918de0a0ec498a044f57c825162513be20de9386/packages/core/src/hooks/useConfig.test.tsx#L29) and we're good to merge.

**Comment by afa7789** [comment]
@rzadp @yivlad done guys :p

**Pull request merged**
