### PR TITLE
👕 Add basic functionality to show/hide the sidebar in example app

### PR DESCRIPTION
**Pull request by JayWelsh**
Recently I wanted to include a video of a bug that happens when using MetaMask Mobile (https://github.com/TrueFiEng/useDApp/issues/1006), however, it was quite problematic to take a video to show the bug due to the Sidebar taking up most of the mobile viewport.

This PR adds some very basic show/hide functionality to the sidebar so that it can be hidden if the need arises (e.g. I would have used the hide option for the video I took in the above bug report).

Video example of feature:

https://user-images.githubusercontent.com/14224459/196434895-c46e4beb-6aa0-46ba-a2c0-3d34adb1abb8.mp4

### CODE REVIEW

**Review by rzadp — APPROVED** [review]
Thanks for introducing this.

**Comment by JayWelsh** [comment]
> Thanks for introducing this.

My pleasure! :)

**Comment by rzadp** [comment]
@JayWelsh Could you run `lint:fix` in the package? I don't have the rights to push onto your fork to do that.

**Comment by JayWelsh** [comment]
Hi @rzadp, what version of `@typescript-eslint/eslint-plugin` are you using?

**Comment by JayWelsh** [comment]
All good @rzadp , managed to get it to run, it didn't make any additional changes beyond the changes I've committed from the `prettier`. Should be all good now :)

**Review by rzadp — APPROVED** [review]

**Pull request closed without merging**
