### PR TITLE
Draft work on CustomError

### PR DESCRIPTION
**Pull request by ItsShadowl**

### CODE REVIEW

**Review by ItsShadowl — COMMENTED** [review]
Will be completing the draft before submitting

**Comment by rzadp** [comment]
@ItsShadowl We have implementation of CustomErrors, working with Hardhat - please take a look into the tests in action here https://github.com/TrueFiEng/Waffle/blob/12c2d7209a310202e8b03862972a88735e5803a0/waffle-hardhat/test/reverted.test.ts#L37

**Comment by ItsShadowl** [comment]
> @ItsShadowl We have implementation of CustomErrors, working with Hardhat - please take a look into the tests in action here https://github.com/TrueFiEng/Waffle/blob/12c2d7209a310202e8b03862972a88735e5803a0/waffle-hardhat/test/reverted.test.ts#L37

The error args and errorName can't be pulled from UseDapp

**Comment by rzadp** [comment]
@ItsShadowl Ah sorry I confused UseDapp with Waffle because I switch from one to another during the day 🤦‍♂️

**Comment by ItsShadowl** [comment]
> @ItsShadowl Ah sorry I confused UseDapp with Waffle because I switch from one to another during the day 🤦‍♂️

I did notice that, LOL

**Comment by pawelpolak2** [comment]
Hey, we'll add it to our roadmap. Closing for now. Please feel free to reopen if needed. 😄

**Pull request closed without merging**
